<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/admin/" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>	
        <link href="assets/images/favicon.ico" rel="apple-touch-icon" type="image/png" sizes="144x144">
        <link href="assets/images/favicon.ico" rel="apple-touch-icon" type="image/png" sizes="114x114">
        <link href="assets/images/favicon.ico" rel="apple-touch-icon" type="image/png" sizes="72x72">
        <link href="assets/images/favicon.ico" rel="apple-touch-icon" type="image/png">
        <link href="assets/images/favicon.ico" rel="icon" type="image/png">
        <link href="assets/images/favicon.ico" rel="shortcut icon">

        <!-- Global stylesheets -->
        <link href="fonts/fonts.css" rel="stylesheet" type="text/css">
        <link href="assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="css/animate.min.css" rel="stylesheet" type="text/css">
        <link href="css/bootstrap.css" rel="stylesheet" type="text/css">
        <link href="css/main.css" rel="stylesheet" type="text/css">
        <link href="css/bootstrap-extended.css" rel="stylesheet" type="text/css">
        <link href="css/plugins.css" rel="stylesheet" type="text/css">
        <link href="css/color-system.css" rel="stylesheet" type="text/css">
        <link href="css/media.css" rel="stylesheet" type="text/css">
        <link href="assets/weather/weather-icons.min.css" rel="stylesheet" type="text/css">
        <link href="assets/weather/weather-icons-wind.min.css" rel="stylesheet" type="text/css">
        <!-- /global stylesheets -->

        <!-- Core JS files -->	
        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>	
        <script src="js/fancybox.min.js"></script>	
        <script src="js/app.js"></script>
    </head>
    <body>
        <?php
        echo $this->render('blocks/navbar.phtml');
        ?>
        <!-- Page container -->
        <div class="page-container" style="min-height:700px">
            <!-- Page content -->
            <div class="page-content">
                <?php echo $this->render('blocks/sidebar.phtml'); ?>
                <!-- Main content -->
                <?php
                echo $this->layout()->content;
                ?>
            </div>
            <!-- /page content -->
        </div>
        <!-- /page container -->
    </body>
</html>