<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav">
    <ul id="slide-out" class="side-nav leftside-navigation">
        <li class="user-details cyan darken-2">
            <div class="row">
                <div class="col col s4 m4 l4">
                    <img src="<?= $this->basePath(); ?>/uploads/companylogo/<?= $this->user["id"]; ?>_avatar.jpeg" alt="" class=" responsive-img valign profile-image" />
                </div>
                <div class="col col s8 m8 l8">
                    <ul id="profile-dropdown" class="dropdown-content">
                        <li><a href="<?= $this->basePath(); ?>/user/profile/"><i class="mdi-action-face-unlock"></i></a></li>
                        <li><a href="#"><i class="mdi-action-settings"></i> settings</a></li>
                        <li><a href="#"><i class="mdi-communication-live-help"></i> help</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="mdi-action-lock-outline"></i> Lock</a></li>
                        <li><a href="/user/logout"><i class="mdi-hardware-keyboard-tab"></i> Logout</a></li>
                    </ul>
                    <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown"><?= $this->user["fullname"]; ?><i class="mdi-navigation-arrow-drop-down right"></i></a>
                    <p class="user-roal">Administrator</p>
                </div>
            </div>
        </li>
        <li class="bold active"><a href="<?= $this->basePath(); ?>" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> homepage</a></li>
        <li class="bold"><a href="<?= $this->basePath(); ?>/loads/myloads/" class="waves-effect waves-cyan"><i class="mdi-communication-email"></i> წერილები <span class="new badge"><?php echo count($this->messages); ?></span></a></li>
        <li class="bold"><a href="<?= $this->basePath(); ?>/filter/" class="waves-effect waves-cyan"><i class="mdi-editor-insert-invitation"></i> ფილტრი</a></li>
        <li class="bold"><a href="<?= $this->basePath(); ?>/messanger/" class="waves-effect waves-cyan"><i class="mdi-editor-insert-invitation"></i> ფილტრი</a></li>
    </ul>
</aside>
<!-- END LEFT SIDEBAR NAV-->