<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="msapplication-tap-highlight" content="no">
        <title><?= $this->headTitle; ?></title>
        <meta name="author" content="Merab Chikvaidze">
        <base href="<?= $this->basePath(); ?>/skin/materialized/" />
        <script>
            var URL = '<?= $this->basePath(); ?>';
            var skinURL = '<?= $this->basePath(); ?>/skin/materialized/';
        </script>

        <!-- Favicons-->
        <link rel="icon" href="images/favicon/favicon-32x32.png" sizes="32x32">
        <!-- Favicons-->
        <link rel="apple-touch-icon-precomposed" href="images/favicon/apple-touch-icon-152x152.png">
        <!-- For iPhone -->
        <meta name="msapplication-TileColor" content="#00bcd4">
        <meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
        <!-- For Windows Phone -->


        <!-- CORE CSS-->    
        <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- CSS for full screen (Layout-2)-->    
        <link href="css/style-fullscreen.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- Custome CSS-->    
        <link href="css/custom-style.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- CSS for full screen (Layout-2)-->    
        <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection">    


        <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
        <link href="js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection" />
        <link href="js/plugins/jvectormap/jquery-jvectormap.css" type="text/css" rel="stylesheet" media="screen,projection" />
        <link href="js/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet" media="screen,projection" />  
        
        <link href="font-awesome-4.5.0/css/font-awesome.min.css" type="text/css" rel="stylesheet" />
<!--        <script type="text/javascript" src="js/angular.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js"></script>
        <script src="js/angularScript.js" ></script>-->
    </head>
    
    <body <?= $this->bodyClass; ?>>
        <!-- Start Page Loading 
        <div id="loader-wrapper">
            <div id="loader"></div>        
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>
        </div>
         End Page Loading -->
        <!-- //////////////////////////////////////////////////////////////////////////// -->
        <?= $this->render('blocks/header.phtml'); ?>
        <!-- //////////////////////////////////////////////////////////////////////////// -->
        <!-- START MAIN -->
        <div id="main">
            <!-- START WRAPPER -->
            <div class="wrapper">
                <?php
                //if ($this->user["type"] == 1)
                    echo $this->render('blocks/left_sidebar_1.phtml');
                //elseif ($this->user["type"] == 2)
                 //   echo $this->render('blocks/left_sidebar_2.phtml');
                ?>
                <!-- START CONTENT -->
                <section id="content">
                    <?php
                    echo $this->content;
                    ?>
                </section>     
                <!-- END CONTENT -->
                <?= $this->render('blocks/right_sidebar.phtml'); ?>        
            </div>
            <!-- END WRAPPER -->
        </div>
        <!-- END MAIN -->
        <?= $this->render('blocks/footer.phtml'); ?>       
        <?= $this->render('blocks/debug.phtml'); ?>       



        <!-- ================================================
        Scripts
        ================================================ -->

        <!-- jQuery Library -->
        <script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>    
        <!--materialize js-->
        <script type="text/javascript" src="js/materialize.js"></script>
        <!--scrollbar-->
        <script type="text/javascript" src="js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
        <!-- chartist -->
        <script type="text/javascript" src="js/plugins/chartist-js/chartist.min.js"></script>   
        <!-- chartjs 
        <script type="text/javascript" src="js/plugins/chartjs/chart.min.js"></script>
        <script type="text/javascript" src="js/plugins/chartjs/chart-script.js"></script> -->
        <!-- sparkline -->
        <script type="text/javascript" src="js/plugins/sparkline/jquery.sparkline.min.js"></script>
        <script type="text/javascript" src="js/plugins/sparkline/sparkline-script.js"></script>
        
        <!--jvectormap-->
        <script type="text/javascript" src="js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        <script type="text/javascript" src="js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <script type="text/javascript" src="js/plugins/jvectormap/vectormap-script.js"></script>   
        <!--plugins.js - Some Specific JS codes for Plugin Settings-->
        <script type="text/javascript" src="js/plugins.js"></script>

        <?php
        $script = null;
        switch ($this->controller) {
            case "loads":
                switch ($this->action) {
                    case "details":
                    case "apply":
                        $script.='<script src="js/ajax.js"></script>';
                        break;
                }
                break;
            case "transporters":
                $script.=' <!-- masonry -->
    <script src="js/plugins/masonry.pkgd.min.js"></script>
    <!-- imagesloaded -->
    <script src="js/plugins/imagesloaded.pkgd.min.js"></script>
    <script>
    var $containerProducts = $("#products");
            $containerProducts.imagesLoaded(function () {
                $containerProducts.masonry({
                    itemSelector: ".product",
                    columnWidth: ".product-sizer",
                });
            });
    </script>';
                break;
            case "bids":
                $script.='<!-- bids page -->'
                    . '<script>'
                    . '$(document).ready(function () {
                            $("ul.collection li.msg_bind_element").click(function () {
                                $(".msg_bind_element").removeClass("active");
                                $(this).addClass("active");
                                var $el = $(this).find("p.text_container");
                                var $showEl=$("div.email-content-wrap");
                                $showEl.find("div.message").html($el.find("span.text").html());
                                $showEl.find("div.row span.email-title").html($el.find("span.fullname").html());
                                $showEl.find("div.row ul.collection li.avatar .circle").attr("src",$el.find("span.company_logo").html());                                 
                            });
                        });</script>';
                break;
        }
        echo $script;
        ?>
        <?= $this->inlineScript() ?>
    </body>
</html>