<?php print_r($tvirtisDetail->getUser()->getFullName()); ?>
<!--breadcrumbs start-->
<div id="breadcrumbs-wrapper" class="white lighten-3">
    <!-- Search for small screen -->
    <div class="header-search-wrapper white hide-on-large-only">
        <i class="mdi-action-search active"></i>
        <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="საძიებო სიტყვა, მაგალითად: საქართველო-იტალია">
    </div>
    <!--card widgets start-->
    <div id="card-widgets" class="seaction">
        <div class="row" style="margin-top: 20px;">
            <div class="col s12 m4 l4">
                <div class="card" id="flight-card" style="margin: 0px;">
                    <div class="card-header amber darken-2">
                        <div class="card-title">
                            <h4 class="flight-card-title"><?= $tvirtisDetail->getUser()->getCompany(); ?></h4>
                            <p class="flight-card-date">June 18, Thu 04:50</p>
                        </div>
                    </div>
                    <div class="card" style="margin: 0px;">
                        <img src="<?= $this->basePath() . '/uploads/companylogo/' . $tvirtisDetail->getUser()->getID(); ?>_avatar.jpeg" alt="<?= $tvirtisDetail->getUser()->getCompany(); ?>" style="width: 100%;margin-top: 0px;" />
                        <p style="padding: 10px;"><?php echo $tvirtisDetail->getComment(); ?></p>
                        <p>
                            <a href="<?= $this->basePath() . '/apply/' . $tvirtisDetail->getUser()->getID(); ?>/">
                                <button class="btn green waves-effect waves-light center">
                                    apply_job <i class="mdi-content-send right"></i>
                                </button>
                            </a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col s12 m4 l4">
                <div class="card" id="flight-card" style="margin: 0px;">
                    <div class="card-header amber darken-2">
                        <div class="card-title">
                            <h4 class="flight-card-title">marshuti_rukaze</h4>
                            <p class="flight-card-date">June 18, Thu 04:50</p>
                        </div>
                    </div>
                    <div class="card" style="margin: 0px;">
                        <div id="map" style="width: 100%;height: 500px;"></div> 
                    </div>
                </div>
            </div>
            <script>
                function initMap() {
                    var directionsService = new google.maps.DirectionsService;
                    var directionsDisplay = new google.maps.DirectionsRenderer;
                    var map = new google.maps.Map(document.getElementById('map'), {zoom: 7,
                        center: {lat: 41.85, lng: -87.65}
                    });
                    directionsDisplay.setMap(map);
                    calculateAndDisplayRoute(directionsService, directionsDisplay);
                }

                function calculateAndDisplayRoute(directionsService, directionsDisplay) {
                    directionsService.route({
                        origin: '<?php echo $this->tvirti["start_direction"]; ?>',
                        destination: '<?php echo $this->tvirti["end_direction"]; ?>',
                        travelMode: google.maps.TravelMode.DRIVING
                    }, function (response, status) {
                        if (status === google.maps.DirectionsStatus.OK) {
                            directionsDisplay.setDirections(response);
                        } else {
                            window.alert('Directions request failed due to ' + status);
                        }
                    });
                }
            </script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCIsda34hufKqa0lZKP3dooe4UmHrqrMKg&signed_in=true&callback=initMap" async defer></script>
            <div class="col s12 m12 l4">
                <div class="card" id="flight-card" style="margin: 0px;">
                    <div class="card-header amber darken-2" style="margin: 0px;">
                        <div class="card-title">
                            <h4 class="flight-card-title">Flight</h4>
                            <p class="flight-card-date">June 18, Thu 04:50</p>
                        </div>
                    </div>
                    <?= $this->render('application/blocks/load_attrs.phtml'); ?> 
                    <div class="col s6 m6 l6 center-align">
                        <div class="flight-info">
                            <p class="small"><span class="text-lighten-4">Depart:</span> 04.50</p>
                            <p class="small"><span class="text-lighten-4">Flight:</span> IB 5786</p>
                            <p class="small"><span class="text-lighten-4">Terminal:</span> B</p>
                        </div>
                    </div>
                    <div class="col s6 m6 l6 center-align flight-state-two">
                        <div class="flight-info">
                            <p class="small"><span class="text-lighten-4">Arrive:</span> 08.50</p>
                            <p class="small"><span class="text-lighten-4">Flight:</span> IB 5786</p>
                            <p class="small"><span class="text-lighten-4">Terminal:</span> C</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>








        <div class="divider"></div>

        <div id="content">
            <div class="grid_container">
                <div class="grid_12" id="tvirtebis_cxrili">
                    <div class="widget_wrap">                                
                        <div class="widget_content">
                            <div class="widget_content field_set">
                                <div id="comments_block">
                                    <?php foreach ($comments as $record): ?>
                                        <div class="row">
                                            <div class="col s12">
                                                <div class="card-panel">
                                                    <p class="left-align"><?= $record->getUser()->getFullName(); ?><i class="mdi-communication-comment"></i><sup><?= $record->getAddDate(); ?></sup></p>
                                                    <p class="left-align"><?= str_replace("\n", "<br />", $record->getComment()); ?></p>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>                       


                                <div id="basic-form" class="section">
                                    <div class="row">
                                        <div class="col s12">
                                            <div class="card-panel">
                                                <h4 class="header2">comment</h4>
                                                <div class="row">
                                                    <div class="row">
                                                        <div class="input-field col s12">
                                                            <textarea class="materialize-textarea" id="comment_box" length="120"></textarea>
                                                            <label for="comment_box">comment</label>
                                                        </div>
                                                    </div>
                                                    <input type="hidden" name="id" value="<?= $tvirtisDetail->getID(); ?>" />
                                                    <div class="row">
                                                        <div class="row">
                                                            <div class="input-field col s12">
                                                                <button class="btn cyan waves-effect waves-light right" type="submit" id="leave_comment" loadid="<?= $tvirtisDetail->getID(); ?>">leave_comment
                                                                    <i class="mdi-communication-comment left"></i>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>